version: '3.8'

services:
  data-ops:
    container_name: chatbot-data-ops
    build:
      context: .
    image: chatbot-data-ops
    env_file:
      - ../.env
    volumes:
      - ./:/src
    networks:
      - chatbot_net

networks:
  chatbot_net:
    external: true
